spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: false

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type: INFO

